---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-htdocs-nginx
  labels:
    app: htdocs-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-htdocs-php
  labels:
    app: htdocs-php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi