FROM nginx:latest

# Create the directory for the shared volume if using Unix socket for communication
# RUN mkdir -p /var/run/php

# Copy the Nginx configuration
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Expose port 8080 for external access
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
