FROM registry.access.redhat.com/ubi9/nginx-122

# Create necessary directories and set permissions
USER root
#RUN mkdir -p /var/cache/nginx/client_temp /var/cache/nginx/proxy_temp /var/cache/nginx/fastcgi_temp /var/cache/nginx/uwsgi_temp /var/cache/nginx/scgi_temp /var/log/nginx /var/www/html \
 #   && chown -R 1001:0 /var/cache/nginx /var/log/nginx /var/www/html \
  # && chmod -R 755 /var/cache/nginx /var/log/nginx /var/www/html

# Copy the Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf
RUN chown default:root /etc/nginx/nginx.conf

RUN mkdir -p /opt/app-root/src/logs/
RUN chown -R default:root /opt/app-root/src/logs/
RUN chmod -R 775 /opt/app-root/src/logs/

# Expose port 8080 for external access
EXPOSE 8080

USER default

# CMD ["nginx", "-g", "daemon off;"]

CMD /usr/libexec/s2i/run