FROM nginx:latest

# Create necessary directories and set permissions
RUN mkdir -p /var/cache/nginx/client_temp /var/cache/nginx/proxy_temp /var/cache/nginx/fastcgi_temp /var/cache/nginx/uwsgi_temp /var/cache/nginx/scgi_temp /var/log/nginx /var/www/html \
    && chown -R 1001:0 /var/cache/nginx /var/log/nginx /var/www/html \
    && chmod -R 755 /var/cache/nginx /var/log/nginx /var/www/html

# Copy the Nginx configuration
COPY .ContainerFiles/nginx/nginx.conf /etc/nginx/nginx.conf

# Expose port 8080 for external access
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
