# Use Red Hat's Universal Base Image with PHP 8.1
FROM registry.access.redhat.com/ubi9/php-81

USER root

# Install system dependencies
RUN yum update -y && yum install -y \
    mariadb \
    freetype \
    libjpeg-turbo \
    libpng \
    libzip \
    unzip \
    git \
    vim-minimal \
    && yum clean all

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory to where the PHP code should reside
#WORKDIR /var/www/html
RUN mkdir -p /var/www/html/{private,htdocs}

# Copy the application code from the relative path of Dockerfile to the working directory
ADD htdocs /var/www/html/htdocs/
ADD private /var/www/html/private/
COPY composer.json .
COPY composer.lock .

# Install PHP dependencies, ignoring platform reqs
RUN composer install --no-dev --optimize-autoloader --ignore-platform-reqs

ADD htdocs /var/www/html/
ADD private /var/www/html/

# Adjust permissions as needed
RUN chown -R 1001:0 . && chmod -R g=u .

# Run as non-root user
USER 1001
