# Use Red Hat's Universal Base Image with PHP 8.1
FROM registry.access.redhat.com/ubi9/php-81

USER root

# Install system dependencies
RUN yum update -y && yum install -y \
    mariadb \
    freetype \
    libjpeg-turbo \
    libpng \
    libzip \
    unzip \
    git \
    vim-minimal \
    && yum clean all

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory to where the PHP code should reside
#WORKDIR /var/www/html
RUN mkdir -p /var/www/html/{private,htdocs}

# Copy the application code from the relative path of Dockerfile to the working directory
ADD htdocs /var/www/html/htdocs/
ADD private /var/www/html/private/
RUN chown -R default:root /var/www/html/
COPY composer.json .
COPY composer.lock .
COPY httpd.conf /etc/httpd/conf/httpd.conf

# Install PHP dependencies, ignoring platform reqs
RUN composer install --no-dev --optimize-autoloader --ignore-platform-reqs

RUN echo "test webpage" > /var/www/html/index.html
RUN chown default:root /var/www/html/index.html

# Adjust permissions as needed
# RUN chown -R 1001:0 . && chmod -R g=u .

RUN chown -R default:root /var/log/

# Run as non-root user
 USER default

# Set the default command for the resulting image
CMD /usr/libexec/s2i/run
